name: boletas_app
description: "App de boletas digitales"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png